name: Build

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  Run-CI_Demo:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the repository
      - name: Checkout the code
        uses: actions/checkout@v3

      # Step 2: Run labview.exe
      - name: Run LabVIEW
        run: |
          echo "Running LabVIEW"
          labview.exe
     
