name: Build

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  Run-CI_Demo:
    runs-on: self-hosted

    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v4
     
      - name: Run LabVIEW
        # run: "C:\Program Files (x86)\National Instruments\LabVIEW 2024\LabVIEWCLI.exe" --operationName RunVI --viPath "C:\Users\vboxuser\desktop\CI_Helper.vi"
         run: echo "Starting the process..."
        
     
