name: Build

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  Run-CI_Demo:
    runs-on: self-hosted

    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Run Batch script using its absolute path
      - name: Run Batch File on local
        run: CMD /C C:\users\vboxuser\CI_Helper\CI_helper.bat
        shell: cmd
